name: ndowens/PKGBUILDs
on:
  push:
  workflow_dispatch:
  schedule:
  - cron: 53 9 * * *
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  create_pkg:
    runs-on: ubuntu-latest
    container:
      image: cachyos/cachyos-v3:latest
    if: # Unable to map conditional expression to GitHub Actions equivalent
#         (always() && ${{ github.event_name }} == "schedule")
    timeout-minutes: 180
    steps:
    - uses: actions/checkout@v4.2.1
      with:
        fetch-depth: 20
        lfs: true
    - run: export COMMIT_BEFORE_SHA="$(git rev-parse HEAD~1)"
    - run: export COMMIT_SHA="$(git rev-parse HEAD~0)"
    - run: export PKGS=$(git diff $COMMIT_BEFORE_SHA $COMMIT_SHA --name-only | sed -e s,PKGBUILD,,)
    - run: sh entrypoint.sh
    - uses: actions/upload-artifact@v4.2.1
      if: success()
      with:
        name: "${{ github.job }}"
        path: public/
  git_pkg:
    runs-on: ubuntu-latest
    container:
      image: cachyos/cachyos-v3:latest
    if: github.event_type == 'schedule'
    timeout-minutes: 180
    steps:
    - uses: actions/checkout@v4.2.1
      with:
        fetch-depth: 20
        lfs: true
    - run: sh entrypoint-git.sh
    - uses: actions/upload-artifact@v4.2.1
      if: success()
      with:
        name: "${{ github.job }}"
        path: public/
  package:
    needs:
    - create_pkg
    - git_pkg
    runs-on: ubuntu-latest
    container:
      image: cachyos/cachyos-v3:latest
    timeout-minutes: 180
    steps:
    - uses: actions/checkout@v4.2.1
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/download-artifact@v4.2.1
    - run: cd public/
    - run: repo-add local-revan.db.tar.gz *.pkg.tar.zst
    - uses: actions/upload-artifact@v4.2.1
      if: success()
      with:
        name: "${{ github.job }}"
        path: public/
  pages:
    needs: package
    runs-on: ubuntu-latest
    container:
      image: busybox
    timeout-minutes: 180
    steps:
    - uses: actions/checkout@v4.2.1
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/download-artifact@v4.2.1
      with:
        name: package
    - run: echo ""
    - uses: actions/upload-artifact@v4.2.1
      if: success()
      with:
        name: "${{ github.job }}"
        path: public
    - uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        branch: gh-pages
        folder: public
